// Demo catalog data for the AgentReady Commerce feature.
// Ported from the original static prototype (agentready-commerce (1)/app.js).
// Placeholder data only — no backend/database wired up yet.

export const demoProducts = [
  {
    id: "strideflow-aero-2",
    brand: "StrideFlow",
    name: "Aero 2",
    category: "Running shoes",
    vertical: "running",
    icon: "↗",
    price: 179,
    currency: "S$",
    rating: 4.8,
    reviews: 642,
    status: "Published",
    lastUpdated: "2026-07-14",
    description: "A breathable daily trainer for runners building distance in warm, wet climates.",
    idealFor: ["half-marathon training", "daily tempo runs", "humid-climate runners"],
    personas: ["performance-minded beginner", "busy city runner", "humid-climate athlete"],
    useCases: ["half marathon", "daily training", "humid weather", "long runs", "road running"],
    specs: {
      weightG: 218,
      dropMm: 8,
      stackMm: 32,
      climate: "humid and warm",
      breathability: "high",
      support: "neutral",
      width: "standard",
      durabilityKm: 700,
    },
    attributes: [
      ["Weight", "218 g"], ["Drop", "8 mm"], ["Upper", "Engineered mesh"], ["Ride", "Responsive neutral"], ["Climate", "Warm / humid"], ["Expected life", "Up to 700 km"],
    ],
    benefits: ["Moves heat and moisture away from the foot", "Light enough for tempo work without a harsh ride", "Stable neutral platform for everyday mileage"],
    claims: [
      { label: "Breathable upper", detail: "Engineered mesh supports airflow across the forefoot.", evidence: "Internal airflow bench test · 2026-02", verified: true },
      { label: "Lightweight build", detail: "218 g in a men's US 9 sample.", evidence: "Size-weight test · 2026-01", verified: true },
      { label: "Distance ready", detail: "Foam tuned for repeated road mileage.", evidence: "Wear-test panel · 2025-11", verified: true },
    ],
    tradeoffs: ["Standard width only", "Neutral support; not designed for strong overpronation"],
    sustainability: { score: 74, detail: "20% recycled mesh by weight; repairable insole." },
    faqs: ["Is it suitable for humid weather?", "How does the Aero 2 fit?", "What distance is it designed for?"],
    contentGaps: ["No independent wet-grip test published yet"],
  },
  {
    id: "harborstride-tempo",
    brand: "HarborStride",
    name: "Tempo Knit",
    category: "Running shoes",
    vertical: "running",
    icon: "↗",
    price: 149,
    currency: "S$",
    rating: 4.6,
    reviews: 284,
    status: "Needs enrichment",
    lastUpdated: "2026-05-04",
    description: "An easygoing knit trainer with a soft landing for city mileage.",
    idealFor: ["easy runs", "new runners"],
    personas: ["first-time runner", "comfort seeker"],
    useCases: ["daily training", "road running", "easy runs"],
    specs: { weightG: 276, dropMm: 10, stackMm: 30, climate: "warm", breathability: "medium", support: "neutral", width: "standard" },
    attributes: [["Weight", "276 g"], ["Drop", "10 mm"], ["Upper", "Knit textile"], ["Ride", "Soft neutral"], ["Climate", "Warm"], ["Width", "Standard"]],
    benefits: ["Soft cushioning for lower-intensity runs", "Stretch knit upper feels accommodating", "Accessible price for a first daily trainer"],
    claims: [{ label: "Soft landing", detail: "Dual-density foam balances step-in comfort and stability.", evidence: "Compression test · 2025-08", verified: true }],
    tradeoffs: ["Heavier than a race-oriented trainer", "Humidity breathability is not independently verified"],
    sustainability: { score: 61, detail: "Blended knit upper; packaging is FSC-certified." },
    faqs: ["Is the knit upper breathable?"],
    contentGaps: ["No measured durability range", "No climate-specific performance evidence"],
  },
  {
    id: "volt-carbon-racer",
    brand: "Volt Athletics",
    name: "Carbon Racer X",
    category: "Running shoes",
    vertical: "running",
    icon: "↗",
    price: 239,
    currency: "S$",
    rating: 4.7,
    reviews: 198,
    status: "Published",
    lastUpdated: "2026-06-21",
    description: "A highly propulsive race-day shoe for experienced runners chasing a faster split.",
    idealFor: ["race day", "half-marathon racing", "speed sessions"],
    personas: ["experienced racer", "time-focused athlete"],
    useCases: ["half marathon", "race day", "speed work", "road running"],
    specs: { weightG: 198, dropMm: 6, stackMm: 38, climate: "warm", breathability: "high", support: "neutral", width: "standard", durabilityKm: 450 },
    attributes: [["Weight", "198 g"], ["Drop", "6 mm"], ["Plate", "Carbon composite"], ["Ride", "Propulsive"], ["Climate", "Warm"], ["Expected life", "Up to 450 km"]],
    benefits: ["Very low weight for race efforts", "High energy return at faster paces", "Secure upper for a locked-in fit"],
    claims: [{ label: "Race-oriented", detail: "Carbon-composite plate and high-return foam are tuned for speed.", evidence: "Materials specification · 2026-03", verified: true }, { label: "Lightweight build", detail: "198 g in a men's US 9 sample.", evidence: "Size-weight test · 2026-03", verified: true }],
    tradeoffs: ["Above the S$200 budget in this query", "Less forgiving for slow daily mileage", "Shorter expected life than a daily trainer"],
    sustainability: { score: 52, detail: "Limited recycled content; replaceable insole." },
    faqs: ["Is it suitable for beginners?", "How long does the foam last?"],
    contentGaps: ["No humid-climate test data"],
  },
  {
    id: "purekind-oil-balance",
    brand: "PureKind",
    name: "Oil Balance 3-Step",
    category: "Skincare routine",
    vertical: "skincare",
    icon: "✦",
    price: 78,
    currency: "S$",
    rating: 4.7,
    reviews: 511,
    status: "Published",
    lastUpdated: "2026-07-30",
    description: "A simple morning routine with cleanser, niacinamide serum, and lightweight SPF for oily skin.",
    idealFor: ["oily and combination skin", "five-minute mornings", "first skincare routine"],
    personas: ["time-poor professional", "ingredient-conscious beginner", "humid-climate commuter"],
    useCases: ["oily skin", "morning routine", "humid weather", "under five minutes", "sustainable skincare"],
    specs: { steps: 3, minutes: 4, skinType: "oily / combination", climate: "humid and warm", spf: 30, fragrance: "fragrance-free", refillable: true },
    attributes: [["Steps", "3"], ["Time", "4 min"], ["Skin type", "Oily / combination"], ["SPF", "30"], ["Scent", "Fragrance-free"], ["Packaging", "Refillable serum"]],
    benefits: ["Cleans without a tight after-feel", "Lightweight hydration that layers under SPF", "Refill format reduces packaging for the serum step"],
    claims: [{ label: "Fragrance-free", detail: "No added fragrance in the three products.", evidence: "INCI review · 2026-04", verified: true }, { label: "Refillable serum", detail: "The 30 ml serum has a mail-back refill format.", evidence: "Packaging specification · 2026-05", verified: true }, { label: "Four-minute routine", detail: "Three steps with a recommended 45-second cleanse.", evidence: "Routine timing study · 2026-02", verified: true }],
    tradeoffs: ["SPF 30 may be insufficient for prolonged midday sun; reapply as directed", "Routine is optimized for oil control, not rich barrier repair"],
    sustainability: { score: 92, detail: "Refillable serum, 80% post-consumer recycled cartons, no outer plastic." },
    faqs: ["Is it suitable for oily skin?", "How long does the routine take?", "Which step is refillable?", "Is it fragrance-free?"],
    contentGaps: ["No public third-party sustainability audit"],
  },
  {
    id: "dewform-gel-routine",
    brand: "Dewform",
    name: "Daily Gel Set",
    category: "Skincare routine",
    vertical: "skincare",
    icon: "✦",
    price: 52,
    currency: "S$",
    rating: 4.5,
    reviews: 329,
    status: "Published",
    lastUpdated: "2026-06-17",
    description: "A compact gel cleanser and moisturizer duo for low-effort daily hydration.",
    idealFor: ["simple routines", "oily and combination skin", "budget-conscious shoppers"],
    personas: ["minimalist", "student", "routine beginner"],
    useCases: ["oily skin", "morning routine", "under five minutes", "travel skincare"],
    specs: { steps: 2, minutes: 3, skinType: "oily / combination", climate: "warm", spf: 0, fragrance: "lightly scented", refillable: false },
    attributes: [["Steps", "2"], ["Time", "3 min"], ["Skin type", "Oily / combination"], ["SPF", "None"], ["Scent", "Lightly scented"], ["Packaging", "Recyclable tube"]],
    benefits: ["Two steps for a quick morning reset", "Gel textures feel light in warm weather", "Lower entry price for a basic routine"],
    claims: [{ label: "Three-minute routine", detail: "Two-step sequence designed for quick mornings.", evidence: "Routine timing study · 2025-12", verified: true }],
    tradeoffs: ["No SPF included", "Lightly scented", "No refill option"],
    sustainability: { score: 68, detail: "Recyclable mono-material tubes; no refill system." },
    faqs: ["Does it include SPF?", "Is it fragrance-free?"],
    contentGaps: ["No ingredient-level oil-control evidence", "Sustainability claim lacks packaging weight"],
  },
  {
    id: "clearleaf-balance-system",
    brand: "ClearLeaf",
    name: "Balance + Shield",
    category: "Skincare routine",
    vertical: "skincare",
    icon: "✦",
    price: 119,
    currency: "S$",
    rating: 4.8,
    reviews: 176,
    status: "Needs enrichment",
    lastUpdated: "2026-03-08",
    description: "A four-product routine pairing gentle cleansing, balancing serum, moisturizer, and SPF.",
    idealFor: ["oily skin", "layered routines", "daily sun protection"],
    personas: ["skincare enthusiast", "urban commuter"],
    useCases: ["oily skin", "morning routine", "sun protection"],
    specs: { steps: 4, minutes: 7, skinType: "oily", climate: "warm", spf: 50, fragrance: "fragrance-free", refillable: false },
    attributes: [["Steps", "4"], ["Time", "7 min"], ["Skin type", "Oily"], ["SPF", "50"], ["Scent", "Fragrance-free"], ["Packaging", "Glass jars"]],
    benefits: ["Higher SPF for daily outdoor exposure", "Four-step sequence supports a complete routine", "Fragrance-free formula family"],
    claims: [{ label: "SPF 50", detail: "Broad-spectrum SPF 50 in the final step.", evidence: "Product label review · 2026-01", verified: true }],
    tradeoffs: ["Takes longer than five minutes", "Heavier glass packaging", "Above the stated budget if bundled with refills"],
    sustainability: { score: 58, detail: "Glass jars, but no refill pathway currently published." },
    faqs: ["How many steps are there?", "Is it suitable for oily skin?"],
    contentGaps: ["No routine timing evidence", "No refill or end-of-life guidance"],
  },
  {
    id: "quietair-mini",
    brand: "QuietAir",
    name: "Mini HEPA 20",
    category: "Air purifier",
    vertical: "air",
    icon: "≈",
    price: 229,
    currency: "S$",
    rating: 4.6,
    reviews: 403,
    status: "Published",
    lastUpdated: "2026-07-02",
    description: "A compact HEPA purifier with a low-noise sleep mode for bedrooms and study spaces.",
    idealFor: ["small bedrooms", "sleeping", "study desks", "rental apartments"],
    personas: ["light sleeper", "city renter", "allergy-aware household"],
    useCases: ["small bedroom", "quiet sleep", "air quality", "under S$300", "compact spaces"],
    specs: { coverageM2: 20, noiseDb: 24, filter: "True HEPA H13 + carbon", cadrM3H: 170, sleepMode: true, energyW: 6 },
    attributes: [["Coverage", "20 m²"], ["Sleep noise", "24 dB"], ["Filter", "HEPA H13 + carbon"], ["CADR", "170 m³/h"], ["Sleep mode", "Yes"], ["Power", "6 W"]],
    benefits: ["Quiet enough for sleep and focused work", "Compact footprint for bedside tables", "Carbon layer helps with common household odors"],
    claims: [{ label: "24 dB sleep mode", detail: "Measured at one meter in the lowest fan mode.", evidence: "Acoustic test · 2026-02", verified: true }, { label: "20 m² coverage", detail: "Recommended room size at the published air-change target.", evidence: "CADR calculation · 2026-02", verified: true }, { label: "HEPA H13", detail: "True HEPA H13 filter media in the replacement cartridge.", evidence: "Filter specification · 2026-01", verified: true }],
    tradeoffs: ["Designed for rooms up to 20 m²", "Filter replacement recommended every 6–9 months", "No app or remote control"],
    sustainability: { score: 71, detail: "Low-power sleep mode; filter cartridge is not yet take-back enabled." },
    faqs: ["Is it quiet enough for sleep?", "How large a room can it cover?", "How often should I replace the filter?"],
    contentGaps: ["No independent clean-air delivery verification"],
  },
  {
    id: "breezesense-bedroom-pro",
    brand: "BreezeSense",
    name: "Bedroom Pro",
    category: "Air purifier",
    vertical: "air",
    icon: "≈",
    price: 299,
    currency: "S$",
    rating: 4.7,
    reviews: 226,
    status: "Published",
    lastUpdated: "2026-06-11",
    description: "A connected purifier for medium bedrooms with automatic particle sensing and quiet night mode.",
    idealFor: ["medium bedrooms", "connected homes", "high-traffic rooms"],
    personas: ["data-minded homeowner", "pet household", "medium-room sleeper"],
    useCases: ["bedroom", "quiet sleep", "air quality", "pet odors", "smart home"],
    specs: { coverageM2: 35, noiseDb: 29, filter: "HEPA H12 + carbon", cadrM3H: 260, sleepMode: true, energyW: 11 },
    attributes: [["Coverage", "35 m²"], ["Sleep noise", "29 dB"], ["Filter", "HEPA H12 + carbon"], ["CADR", "260 m³/h"], ["Sleep mode", "Yes"], ["Power", "11 W"]],
    benefits: ["More airflow for larger bedrooms", "Automatic sensing adjusts to changes in particle levels", "App provides filter-life reminders"],
    claims: [{ label: "35 m² coverage", detail: "Recommended room size at the published air-change target.", evidence: "CADR calculation · 2025-10", verified: true }, { label: "Connected monitoring", detail: "App reports PM2.5 trends and filter life.", evidence: "Feature specification · 2025-10", verified: true }],
    tradeoffs: ["At the upper edge of the S$300 budget", "29 dB sleep mode is audible in very quiet rooms", "Higher power draw than a compact model"],
    sustainability: { score: 66, detail: "Replaceable filter and auto-sleep mode; no take-back program." },
    faqs: ["Can it cover a large bedroom?", "Does it have an app?"],
    contentGaps: ["No independently measured sleep-mode noise evidence"],
  },
];

export const goldenQueries = [
  { query: "I'm training for a half marathon in Singapore's humid weather and need lightweight shoes under S$200.", label: "Performance + climate + budget", vertical: "running" },
  { query: "Find me a sustainable skincare routine for oily skin that takes less than 5 minutes every morning.", label: "Persona + sustainability + time", vertical: "skincare" },
  { query: "I need a quiet air purifier for a small bedroom under S$300.", label: "Room size + noise + budget", vertical: "air" },
  { query: "Which running shoes are best for a beginner's easy runs under S$160?", label: "Experience level + use case + budget", vertical: "running" },
  { query: "What is the fastest fragrance-free morning skincare routine for oily skin?", label: "Time + ingredient preference", vertical: "skincare" },
  { query: "Which purifier has the lowest sleep noise for a 20 square meter bedroom?", label: "Numeric comparison + room size", vertical: "air" },
];
